image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

services:
  - mssql2016

environment:
  "roundhouse:tests:connectionstring:sqlserver": "Server=(local)\\SQL2016;Database=master;User ID=sa;Password=Password12!"
  "roundhouse:tests:connectionstring:sqlserver": "server=localhost;uid=root;Password=Password12!"
  
before_build:
  - ps: gitversion /l console /output buildserver

build_script:
  - ps: .\build.ps1

test:
  assemblies:
    only:
    - '**\*tests.dll'- '**\*tests.integration.dll'
artifacts:
  - path: .\code_drop\packages\*.nupkg
    name: Nuget packages
  - path: .\code_drop\log\*
    name: Logs