pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Build'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@3

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: /t:"Build;Pack" 

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


#- powershell:  |
    #.\build.ps1
# - script:  |
#     %comspec% /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\VsDevCmd.bat" & powershell.exe .\build.ps1"
#   displayName: 'Build.ps1'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: '.\code_drop\packages\*.nupkg' 
#     artifactName: 'Nuget packages' 
#     publishLocation: 'Container' # Options: container, filePath
#     #targetPath: # Required when publishLocation == FilePath
#     #parallel: false # Optional
#     #parallelCount: # Optional

#   #- path: .\code_drop\log\*
#     #name: Logs
