pool:
  vmImage: 'Hosted VS2017'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@3

- powershell: |
    $Version = "4.8.1";
    try {
      Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v$Version/nuget.exe" -OutFile "$env:BUILD_BINARIESDIRECTORY\nuget.exe"
      Write-Host "##vso[task.setvariable variable=Path;]$env:BUILD_BINARIESDIRECTORY;$env:Path"
    } catch {Write-Error -Message "Failed to download nuget.exe from $urlPrefix.  $($_.Exception.Message)" -ErrorAction Stop}
  displayName: 'Get nuget.exe'


- powershell: .\build.ps1
  displayName: 'Build.ps1'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.binariesdirectory)' 
    #artifactName: '' 
    publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
